language: objective-c
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
before_install:
  - gem install xcpretty
script:
  - rake "clean[JavaScriptBridge.xcworkspace, 'JavaScriptBridgeApp libJavaScriptBridge UICatalog HelloWorld']"
  - rake "build[JavaScriptBridge.xcworkspace, 'JavaScriptBridgeApp libJavaScriptBridge UICatalog HelloWorld']"
  - rake "test[JavaScriptBridge.xcworkspace, 'libJavaScriptBridge']"
   
